apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: otaadmin-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
  minReadySeconds: 30
  template:
    metadata:
      labels:
        app: otaadmin-pod
    spec:
      containers:
      - name: otaadmin-container
        image: nuwarobotics/otaadmin:latest
        imagePullPolicy: Always
        command: ["/bin/bash","-c"]
        args: ["gunicorn -b :5000 0b unix:/tmp/gunicorn.sock -c config/gunicorn.py ota:create_application()"]
        ports:
        - name: otaadmin-port
          containerPort: 5000
