apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fps-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
  minReadySeconds: 30
  template:
    metadata:
      labels:
        app: fps-pod
    spec:
      containers:
      - name: otaadmin-container
        image: nuwarobotics/fps:latest
        imagePullPolicy: Always
        command:
        - /bin/bash
        - -c
        - gunicorn -b :5001 -b unix:/tmp/gunicorn.sock -c config/gunicorn.py "fps:create_application()"
        ports:
        - name: fps-port
          containerPort: 5001
        env:
        - name: LANG
          value: 'en_US.UTF-8'
        - name: PYTHONUNBUFFERED
          value: "True"
        - name: PYTHONIOENCODING
          value: utf-8
        - name: SETTINGS_MODULE
          value: fps.settings.local
        - name: SECRET_KEY
          value: secret_key
        - name: DATABASE_URL
          value: mongodb://10.1.101.10:27017/fps
        - name: CACHE_URL_DEFAULT 
          value: redis://10.1.101.10:6379/1
        - name: CELERY_BROKER_URL
          value: redis://10.1.101.10:6379/2
        - name: CELERY_RESULT_BACKEND
          value: redis://10.1.101.10:6379/3
        - name: CELERY_TIMEZONE
          value: "Asia/Taipei"
        - name: MAIL_SERVER_URL
          value: smtp://postmaster@iavnight.com:6250d06801b0c12b55ac5b6e497ca9c4@smtp.mailgun.org:587?tls=1
        - name: MAILGUN_DOMAIN
          value: postmaster@iavnight.com
        - name: MAILGUN_API_KEY
          value: key-135c007ee2402644de14430d4140e5a3
        - name: VERIFY_KEY
          value: efjqfh3iufhoi4f3jf434opf
        - name: AWS_ACCESS_KEY_ID
          value: AKIAJJIMGHNO3KUQUANA
        - name: AWS_SECRET_ACCESS_KEY
          value: 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
        - name: S3_BUCKET
          value: dev-nuwarobotics-mibo-pet-resources
        - name: FPS_URL
          value: http://dev-file.nuwarobotics.com/v1/
        livenessProbe:
          tcpSocket:
            port: 5001
          initialDelaySeconds: 15
          timeoutSeconds: 30
      imagePullSecrets:
      - name: regsecret

