apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  containers:
    - name: private-reg-container
      image: chenjohn/test:1
      command: ["/bin/bash","-c"]
      args: ["python3 /root/app.py"]
      ports:
      - name: private-port
        containerPort: 80
  imagePullSecrets:
    - name: regsecret
