apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: flask-replicaset
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  # labels:
    # app: guestbook
    # tier: frontend
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 3
  # selector can be applied automatically
  # from the labels in the pod template if not set,
  # but we are specifying the selector here to
  # demonstrate its usage.
  #selector:
  #  matchLabels:
  #    tier: frontend
  #  matchExpressions:
  #    - {key: tier, operator: In, values: [frontend]}
  template:
    metadata:
      labels:
        app: flask-pod
  #      tier: frontend
    spec:
      containers:
      - name: flask-ct
        image: chihchinag/flask:4
        command: ["/bin/bash","-c"]
        args: ["python3 /root/app.py"]
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        #env:
        #- name: GET_HOSTS_FROM
        #  value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below.
          # value: env
        ports:
        ports:
        - name: flask-port
          containerPort: 80
