apiVersion: v1
kind: Service
metadata:
  name: flask-deployment
spec:
  ports:
  - port: 80
    targetPort: flask-port
    nodePort: 31111
    protocol: TCP
  selector:
    app: flask-pod
  type: NodePort
