apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: flask-pod
    spec:
      containers:
      - name: flask
        image: chihchinag/flask
        ports:
        - name: flask-port
          containerPort: 80
      nodeSelector:
        hardware: high-spec
