apiVersion: v1
kind: LimitRange
metadata:
  name: memory-maxmin
spec:
  limits:
  - default:
      memory: 510Mi
    defaultRequest:
      memory: 500Mi
    max:
      memory: 512Mi
    min:
      memory: 256Mi
    type: Container
