apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: flask-deployment-scaler
spec:
  scaleTargetRef:
    kind: Deployment
    name: flask-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 5
