apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: flask-pod
    spec:
      containers:
      - name: flask-ct
        image: chihchinag/flask:10
        command: ["/bin/bash","-c"]
        args: ["python3 /root/app.py"]
        ports:
        - name: flask-port
          containerPort: 80
      nodeSelector:
        zone: 1a
