apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: prometheus-node-exporter
spec:
  template:
    metadata:
      labels:
        daemon: prom-node-exp
    spec:
      containers:
      - name: c
        image: prom/prometheus
        ports:
        - name: serverport
          containerPort: 9090
          hostPort: 9090
