apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: flask-scaler
spec:
  scaleTargetRef:
    kind: ReplicaSet
    name: flask-rs
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
